### ISSUE TITLE
[BUG] Failed to install with current node LTS version: 20.9.0

### ISSUE THREAD

**Issue by 101sam** [DanielPantle/strapi-plugin-react-icons#19]
## Bug report

The current [LTS version is 20.9.0 ](https://nodejs.org/en)

This module is broken on all our servers using strapi 

### Required System information

- Node.js version: 20.9.0 LTS
- NPM version: 10.2.1
- Strapi version: 4.15.0
- Database: MySQL
- Operating system: Tested on: Linux & Mac
- Project Javascript

### Describe the bug

failed to install 

`yarn install `or `npm install`

### Expected behavior

Need to bump up the plugin packages

### Screenshots

NA

### Code snippets

NA

### Additional context

It would be nice to have some automatic process to test all strapi marketplace plugins before bumping versions with the latest LTS.  It does not make sense to have a marketplace plugin with limited versions that are less than the current strapi version. It's breaking servers.

I will add to the marketplace a field test on LTS: version(s) and date so at least before upgrading the node version we will know.

**Comment by DanielPantle** [comment]
Thanks for your report. I just tested the newest version of the plugin with node version v20.9.0 and a fresh strapi installation and it works fine for me. @101sam please test again if after the changes of #18 the package works for you.

**Comment by DanielPantle** [comment]
Closing the issue. @101sam if it occurs again, please re-open.
