### ISSUE TITLE
Add PhosphorIcons Support

### ISSUE THREAD

**Issue by gustaelesbao** [DanielPantle/strapi-plugin-react-icons#2]
It would be great to add an integration with the lib PhosphorIcons, as it has a plethora of icons and styles.
Lib link: https://phosphoricons.com/

**Comment by DanielPantle** [comment]
Thanks for your idea! Unfortunately, afaics PhosphorIcons are not part of the [react-icons library](https://react-icons.github.io/react-icons/) this plugin uses. Therefore it is not possible to easily support them and would also not fit in the scope of this library.
But feel free to use the code of this plugin to create one for PhosphorIcons!
