### ISSUE TITLE
Extension Not showing after npm run build

### ISSUE THREAD

**Issue by leonardopironti** [DanielPantle/strapi-plugin-react-icons#6]
Could you please provide the /config/plugins.ts configuration for this extension?

**Comment by DanielPantle** [comment]
Hi @leonardopironti :)

The /config/plugins.ts should look like this:
`
export default ({ env }) => ({
  "react-icons": true,
});
`

For javascript, it would be:
`
module.exports = ({ env }) => ({
  "react-icons": true,
});
`

**Comment by DanielPantle** [comment]
I added this info also in the readme. Thanks for the hint ;)
