### ISSUE TITLE
Npm error in  strapi v4.11.0 

### ISSUE THREAD

**Issue by yusuf-saydullayev** [DanielPantle/strapi-plugin-react-icons#7]
npm ERR! Found: styled-components@5.3.3
npm ERR! node_modules/styled-components
npm ERR!   styled-components@"5.3.3" from @strapi/admin@4.11.0
npm ERR!   node_modules/@strapi/admin
npm ERR!     @strapi/admin@"4.11.0" from @strapi/strapi@4.11.0
npm ERR!     node_modules/@strapi/strapi
npm ERR!       peer @strapi/strapi@"^4.3.4" from @strapi/admin@4.11.0
npm ERR!       5 more (@strapi/data-transfer, @strapi/plugin-color-picker, ...)
npm ERR!   peer styled-components@"^5.2.1" from @strapi/design-system@1.8.0
npm ERR!   node_modules/@strapi/design-system
npm ERR!     @strapi/design-system@"1.8.0" from @strapi/admin@4.11.0
npm ERR!     node_modules/@strapi/admin
npm ERR!       @strapi/admin@"4.11.0" from @strapi/strapi@4.11.0
npm ERR!       node_modules/@strapi/strapi
npm ERR!         peer @strapi/strapi@"^4.3.4" from @strapi/admin@4.11.0
npm ERR!         5 more (@strapi/data-transfer, @strapi/plugin-color-picker, ...)
npm ERR!     peer @strapi/design-system@"1.8.0" from @strapi/helper-plugin@4.11.0

**Comment by yusuf-saydullayev** [comment]
package version conflict

**Comment by DanielPantle** [comment]
@yusuf-saydullayev Thanks for reporting! Unfortunately I do not know yet how to fix it. For now, you can use `npm i --force`. If you know how this can be fixed, feel free to create a PR :)

**Comment by yusuf-saydullayev** [comment]
I think need to update devDependencies and peerDependencies

**Comment by yusuf-saydullayev** [comment]
In v4.11.0 strapi used react v18
